"""Fine-tune Grounding DINO using verified primary-subject boxes.

Consumes the shared subject-layer manifest generated by
``train_florence_subject_captions.py``. Each photo contributes its reviewed
primary box and subject phrase. The phrase is supplied as the text prompt, and
its first tokenizer position is used as the positive class target for the
Transformers GroundingDINO bipartite matching loss.

This script does not start training unless ``--train`` is explicitly passed.
CUDA is required by default; ``--allow-cpu`` is an explicit opt-in to a very
slow CPU run.
"""

from __future__ import annotations

import argparse
import json
import random
import time
from collections import Counter
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
MODEL_ROOT = ROOT / "algorithms" / "models" / "IDEA-Research__grounding-dino-tiny"
DEFAULT_MANIFEST = ROOT / "artifacts" / "subject_layer_florence_caption_ft" / "subject_caption_manifest.jsonl"
DEFAULT_OUTPUT = ROOT / "artifacts" / "subject_layer_grounding_dino_ft"
FALLBACK_PROMPTS = {
    "人像": "person",
    "风光摄影": "landscape",
    "静物摄影": "object",
    "活动事件摄影": "event scene",
}


def _grounding_phrase(row: dict[str, Any]) -> tuple[str, bool]:
    """Return a semantic prompt; review-operation tags are not object names."""
    if row.get("prompt_mode") == "fixed_main_subject":
        return "main subject", False
    label = " ".join(str(row["primary_subject_label"]).strip().lower().split())
    if label and not label.startswith("human_review_") and label != "person (manual review)":
        return label, False
    category = row["category"]
    if category not in FALLBACK_PROMPTS:
        raise ValueError(f"No GroundingDINO fallback prompt for category {category!r}")
    return FALLBACK_PROMPTS[category], True


def _read_manifest(path: Path) -> list[dict[str, Any]]:
    rows = []
    seen = set()
    groups: dict[str, set[str]] = {}
    with path.open("r", encoding="utf-8-sig") as stream:
        for line_number, line in enumerate(stream, 1):
            if not line.strip():
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid manifest JSON at line {line_number}: {exc}") from exc
            required = {
                "image_id", "category", "source_path", "primary_subject_label",
                "primary_subject_box_xywh_norm", "split", "group_id",
            }
            if not required.issubset(row):
                missing = sorted(required - set(row))
                raise ValueError(f"Manifest line {line_number} missing detector fields: {missing}")
            if row["image_id"] in seen:
                raise ValueError(f"Duplicate image_id in manifest: {row['image_id']}")
            seen.add(row["image_id"])
            if row["split"] not in {"train", "validation", "test"}:
                raise ValueError(f"Invalid split on manifest line {line_number}: {row['split']}")
            source = Path(row["source_path"])
            if not source.is_file():
                raise FileNotFoundError(f"Missing source image: {source}")
            label = row["primary_subject_label"]
            box = row["primary_subject_box_xywh_norm"]
            if not isinstance(label, str) or not label.strip() or not isinstance(box, list) or len(box) != 4:
                raise ValueError(f"Missing subject phrase/box on manifest line {line_number}")
            x, y, width, height = map(float, box)
            if x < 0 or y < 0 or width <= 0 or height <= 0 or x + width > 1.00001 or y + height > 1.00001:
                raise ValueError(f"Invalid normalized xywh box on line {line_number}: {box}")
            group_id = row["group_id"]
            groups.setdefault(group_id, set()).add(row["split"])
            rows.append(row)
    if not rows:
        raise ValueError(f"Empty detector manifest: {path}")
    leaking = [group for group, splits in groups.items() if len(splits) > 1]
    if leaking:
        raise ValueError(f"Duplicate groups cross data splits: {leaking[:5]}")
    return rows


def _token_start(input_ids: Any, phrase_ids: list[int], image_id: str) -> int:
    ids = input_ids[0].tolist()
    if not phrase_ids:
        raise ValueError(f"Subject phrase has no tokens for {image_id}")
    for start in range(0, len(ids) - len(phrase_ids) + 1):
        if ids[start:start + len(phrase_ids)] == phrase_ids:
            return start
    raise ValueError(f"Subject phrase tokens not found in model prompt for {image_id}")


def _target_box(box_xywh: list[float], torch: Any, device: str) -> Any:
    x, y, width, height = map(float, box_xywh)
    # GroundingDINO/DETR loss expects normalized center-x, center-y, width, height.
    return torch.tensor([[x + width / 2, y + height / 2, width, height]], dtype=torch.float32, device=device)


def _box_iou(predicted_cxcywh: Any, target_cxcywh: Any) -> float:
    def corners(box: Any) -> tuple[float, float, float, float]:
        cx, cy, width, height = [float(value) for value in box]
        return cx - width / 2, cy - height / 2, cx + width / 2, cy + height / 2

    ax1, ay1, ax2, ay2 = corners(predicted_cxcywh)
    bx1, by1, bx2, by2 = corners(target_cxcywh)
    intersection = max(0.0, min(ax2, bx2) - max(ax1, bx1)) * max(0.0, min(ay2, by2) - max(ay1, by1))
    area_a = max(0.0, ax2 - ax1) * max(0.0, ay2 - ay1)
    area_b = max(0.0, bx2 - bx1) * max(0.0, by2 - by1)
    union = area_a + area_b - intersection
    return intersection / union if union > 0 else 0.0


def _batch(model: Any, processor: Any, image: Any, row: dict[str, Any], torch: Any, device: str) -> tuple[dict[str, Any], dict[str, Any], int]:
    phrase, _ = _grounding_phrase(row)
    inputs = processor(images=image, text=phrase + ".", return_tensors="pt")
    inputs = {key: value.to(device) for key, value in inputs.items() if hasattr(value, "to")}
    phrase_ids = processor.tokenizer(
        phrase.rstrip("."), add_special_tokens=False
    )["input_ids"]
    token_index = _token_start(inputs["input_ids"], phrase_ids, row["image_id"])
    if token_index >= int(model.config.max_text_len):
        raise ValueError(f"Subject phrase token index exceeds GroundingDINO max_text_len: {row['image_id']}")
    target = {
        "class_labels": torch.tensor([token_index], dtype=torch.long, device=device),
        "boxes": _target_box(row["primary_subject_box_xywh_norm"], torch, device),
    }
    return inputs, target, token_index


def _evaluate(model: Any, processor: Any, rows: list[dict[str, Any]], torch: Any, image_cls: Any, device: str) -> dict[str, Any]:
    model.eval()
    losses, ious, recalls = [], [], []
    predictions = []
    with torch.inference_mode():
        for index, row in enumerate(rows, 1):
            with image_cls.open(row["source_path"]) as image:
                image = image.convert("RGB")
                inputs, target, token_index = _batch(model, processor, image, row, torch, device)
                outputs = model(**inputs, labels=[target])
                losses.append(float(outputs.loss.cpu()))
                scores = outputs.logits[0, :, token_index].sigmoid()
                best = int(scores.argmax().item())
                pred = outputs.pred_boxes[0, best].detach().cpu().tolist()
                gt = target["boxes"][0].detach().cpu().tolist()
                iou = _box_iou(pred, gt)
                ious.append(iou)
                recalls.append(float(iou >= 0.5))
                predictions.append(dict(image_id=row['image_id'], category=row['category'],
                                        prediction_cxcywh=pred, target_cxcywh=gt, iou=iou))
            if index % 50 == 0 or index == len(rows):
                print(f"validation {index}/{len(rows)}", flush=True)
    model.train()
    return {
        "count": len(rows),
        "predictions": predictions,
        "loss": sum(losses) / max(1, len(losses)),
        "mean_iou_top_phrase_token": sum(ious) / max(1, len(ious)),
        "recall_iou_0_5_top_phrase_token": sum(recalls) / max(1, len(recalls)),
    }


def _balanced_subset(rows: list[dict[str, Any]], limit: int, seed: int) -> list[dict[str, Any]]:
    """Deterministic class-balanced subset; categories used only for sampling."""
    if not limit:
        return rows
    buckets = {}
    for row in sorted(rows, key=lambda r: r['image_id']):
        buckets.setdefault(row['category'], []).append(row)
    rng = random.Random(seed)
    for bucket in buckets.values():
        rng.shuffle(bucket)
    selected = []
    while len(selected) < min(limit, len(rows)):
        for category in sorted(buckets):
            if buckets[category] and len(selected) < limit:
                selected.append(buckets[category].pop())
    return selected


def _train(args: argparse.Namespace) -> dict[str, Any]:
    started = time.perf_counter()
    import torch
    from PIL import Image
    from transformers import AutoModelForZeroShotObjectDetection, AutoProcessor

    torch.set_num_threads(args.cpu_threads)
    torch.manual_seed(args.seed)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    if device == "cpu" and not args.allow_cpu:
        raise RuntimeError("CUDA is unavailable. GroundingDINO fine-tuning on CPU is disabled by default; pass --allow-cpu to opt in.")
    if not MODEL_ROOT.is_dir():
        raise FileNotFoundError(f"Local GroundingDINO model is missing: {MODEL_ROOT}")
    rows = _read_manifest(args.manifest.resolve())
    train_rows = [row for row in rows if row["split"] == "train"]
    validation_rows = [row for row in rows if row["split"] == "validation"]
    if not train_rows or not validation_rows:
        raise ValueError("Manifest must contain both train and validation samples")
    if args.limit_train:
        train_rows = _balanced_subset(train_rows, args.limit_train, args.seed)
    if args.limit_validation:
        validation_rows = _balanced_subset(validation_rows, args.limit_validation, args.seed + 1)

    processor = AutoProcessor.from_pretrained(str(MODEL_ROOT), local_files_only=True)
    model = AutoModelForZeroShotObjectDetection.from_pretrained(str(MODEL_ROOT), local_files_only=True)
    # This installed Transformers version feeds padded -inf text logits to
    # DETR BCE focal loss, which yields NaN even for negative targets. Replace
    # only those masked logits with a finite, effectively-zero probability.
    # Do not hide NaN or positive infinity in actual model activations.
    from transformers.models.grounding_dino.modeling_grounding_dino import GroundingDinoContrastiveEmbedding
    def finite_padding(module: Any, inputs: Any, output: Any) -> Any:
        if torch.isnan(output).any() or torch.isposinf(output).any():
            raise FloatingPointError("Invalid non-padding contrastive logits")
        return output.masked_fill(torch.isneginf(output), -100.0)
    for module in model.modules():
        if isinstance(module, GroundingDinoContrastiveEmbedding):
            module.register_forward_hook(finite_padding)
    # HF GroundingDINO logits are over text-token positions; reserve max_text_len
    # as the no-object sentinel used by the DETR loss implementation.
    model.config.num_labels = int(model.config.max_text_len)
    if args.freeze_backbone:
        backbone = getattr(getattr(model, "model", None), "backbone", None)
        if backbone is None:
            raise RuntimeError("Could not locate GroundingDINO vision backbone for freezing")
        for parameter in backbone.parameters():
            parameter.requires_grad_(False)
    model.to(device)
    model.train()

    setup_seconds = time.perf_counter() - started
    print(f"Model setup: {setup_seconds:.2f}s; device={device}", flush=True)

    output = args.output_dir.resolve()
    if output.exists() and any(output.iterdir()) and not args.overwrite:
        raise FileExistsError(f"Output directory is not empty; choose another path or pass --overwrite: {output}")
    output.mkdir(parents=True, exist_ok=True)
    (output / 'run_config.json').write_text(json.dumps({
        'arguments': {k: str(v) if isinstance(v, Path) else v for k, v in vars(args).items()},
        'train_ids': [r['image_id'] for r in train_rows],
        'validation_ids': [r['image_id'] for r in validation_rows],
        'train_categories': dict(Counter(r['category'] for r in train_rows)),
        'validation_categories': dict(Counter(r['category'] for r in validation_rows)),
        'prompt_modes': dict(Counter(r.get('prompt_mode', 'semantic') for r in train_rows)),
    }, ensure_ascii=False, indent=2), encoding='utf-8')
    baseline = None
    if args.evaluate_before:
        print('Evaluating untouched pretrained baseline on fixed validation subset', flush=True)
        baseline = _evaluate(model, processor, validation_rows, torch, Image, device)
        (output / 'baseline_validation.json').write_text(json.dumps(baseline, ensure_ascii=False, indent=2), encoding='utf-8')
        print(json.dumps({k:v for k,v in baseline.items() if k != 'predictions'}), flush=True)
    optimizer = torch.optim.AdamW(
        [parameter for parameter in model.parameters() if parameter.requires_grad],
        lr=args.learning_rate,
        weight_decay=args.weight_decay,
    )
    random.seed(args.seed)
    history: list[dict[str, Any]] = []
    best_validation = float("inf")
    best_epoch = 0
    best_step = 0
    best_selection_score = (
        (float(baseline["recall_iou_0_5_top_phrase_token"])
         + float(baseline["mean_iou_top_phrase_token"])) / 2.0
        if baseline is not None else float("-inf")
    )
    if baseline is not None:
        best_validation = float(baseline["loss"])
    stale_epochs = 0
    stale_evaluations = 0
    step = 0
    step_seconds = []
    validation_seconds = []
    interval_losses: list[float] = []
    validation = baseline

    def evaluate_checkpoint(epoch: int) -> bool:
        """Evaluate/save an interval checkpoint; return True to stop early."""
        nonlocal validation, best_validation, best_epoch, best_step
        nonlocal best_selection_score, stale_evaluations, interval_losses
        validation_started = time.perf_counter()
        validation = _evaluate(model, processor, validation_rows, torch, Image, device)
        validation_seconds.append(time.perf_counter() - validation_started)
        selection_score = (
            float(validation["recall_iou_0_5_top_phrase_token"])
            + float(validation["mean_iou_top_phrase_token"])
        ) / 2.0
        result = {
            "epoch": epoch,
            "step": step,
            "train_loss_since_previous_evaluation": sum(interval_losses) / max(1, len(interval_losses)),
            "selection_score": selection_score,
            "validation": validation,
        }
        history.append(result)
        compact = {key: value for key, value in validation.items() if key != "predictions"}
        print(json.dumps({"epoch": epoch, "step": step, "selection_score": selection_score,
                          "validation": compact}, ensure_ascii=False), flush=True)
        (output / "training_history.json").write_text(
            json.dumps(history, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        checkpoint = output / f"checkpoint_step_{step:04d}"
        model.save_pretrained(checkpoint, safe_serialization=True)
        processor.save_pretrained(checkpoint)
        if selection_score > best_selection_score + args.min_selection_improvement:
            best_selection_score = selection_score
            best_validation = float(validation["loss"])
            best_epoch = epoch
            best_step = step
            stale_evaluations = 0
            model.save_pretrained(output / "best_model", safe_serialization=True)
            processor.save_pretrained(output / "best_model")
        else:
            stale_evaluations += 1
        interval_losses = []
        (output / 'progress.json').write_text(json.dumps(dict(
            phase='training', completed_steps=step, target_steps=args.max_steps,
            last_validation=compact, best_step=best_step,
            stale_evaluations=stale_evaluations,
            elapsed_seconds=time.perf_counter()-started)), encoding='utf-8')
        return bool(args.early_stop_evaluations and stale_evaluations >= args.early_stop_evaluations)

    for epoch in range(1, args.epochs + 1):
        model.train()
        shuffled = list(train_rows)
        random.Random(args.seed + epoch).shuffle(shuffled)
        losses = []
        for row in shuffled:
            step_started = time.perf_counter()
            with Image.open(row["source_path"]) as image:
                image = image.convert("RGB")
                inputs, target, _ = _batch(model, processor, image, row, torch, device)
                optimizer.zero_grad(set_to_none=True)
                outputs = model(**inputs, labels=[target])
                loss = outputs.loss
                if not torch.isfinite(loss):
                    raise FloatingPointError(f"Non-finite detection loss on {row['image_id']} at epoch {epoch}")
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), args.max_grad_norm, error_if_nonfinite=True)
                optimizer.step()
                losses.append(float(loss.detach().cpu()))
                interval_losses.append(losses[-1])
                step += 1
            duration = time.perf_counter() - step_started
            step_seconds.append(duration)
            print(f"step={step} loss={losses[-1]:.6f} seconds={duration:.2f}", flush=True)
            (output / 'progress.json').write_text(json.dumps(dict(phase='training', completed_steps=step,
                target_steps=args.max_steps, loss=losses[-1], elapsed_seconds=time.perf_counter()-started)), encoding='utf-8')
            if args.eval_every_steps and step % args.eval_every_steps == 0:
                if evaluate_checkpoint(epoch):
                    print(f"Early stopping after {stale_evaluations} stale evaluations at step {step}", flush=True)
                    break
            if args.max_steps and step >= args.max_steps:
                break

        if not args.eval_every_steps:
            evaluate_checkpoint(epoch)
            stale_epochs = stale_evaluations
        elif interval_losses and not (args.max_steps and step >= args.max_steps):
            evaluate_checkpoint(epoch)
        if args.max_steps and step >= args.max_steps:
            break
        if args.early_stop_evaluations and stale_evaluations >= args.early_stop_evaluations:
            break
        if stale_epochs >= args.patience:
            break

    result = {
        "baseline_validation": baseline,
        "final_validation": validation,
        "setup_seconds": setup_seconds,
        "training_step_seconds": step_seconds,
        "validation_seconds": validation_seconds,
        "elapsed_seconds": time.perf_counter() - started,
        "completed_steps": step,
        "cpu_threads": args.cpu_threads,
        "base_model": str(MODEL_ROOT),
        "manifest": str(args.manifest.resolve()),
        "device": device,
        "train_photos": len(train_rows),
        "validation_photos": len(validation_rows),
        "test_photos_reserved": sum(row["split"] == "test" for row in rows),
        "best_epoch": best_epoch,
        "best_step": best_step,
        "best_selection_score": best_selection_score,
        "best_validation_loss": best_validation,
        "test_split_used_for_optimization": False,
        "freeze_backbone": args.freeze_backbone,
        "box_target": "primary_subject_box_xywh_norm converted to normalized cxcywh",
        "class_target": "first token position of semantic GroundingDINO prompt",
        "category_fallback_prompt_photos": sum(_grounding_phrase(row)[1] for row in rows),
    }
    (output / "training_summary.json").write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    (output / 'progress.json').write_text(json.dumps(dict(phase='completed', completed_steps=step,
        elapsed_seconds=time.perf_counter()-started)), encoding='utf-8')
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--dry-run", action="store_true", help="validate manifest and report counts without loading the model")
    parser.add_argument("--train", action="store_true", help="start detector fine-tuning; omitted by default")
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--cpu-threads", type=int, default=8)
    parser.add_argument("--evaluate-before", action="store_true")
    parser.add_argument("--eval-every-steps", type=int, default=0)
    parser.add_argument("--early-stop-evaluations", type=int, default=0)
    parser.add_argument("--min-selection-improvement", type=float, default=0.002)
    parser.add_argument("--patience", type=int, default=4)
    parser.add_argument("--learning-rate", type=float, default=1e-5)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--max-grad-norm", type=float, default=0.1)
    parser.add_argument("--seed", type=int, default=1337)
    parser.add_argument("--max-steps", type=int, default=0, help="optional smoke-test cap")
    parser.add_argument("--limit-train", type=int, default=0, help="optional smoke-test cap")
    parser.add_argument("--limit-validation", type=int, default=0, help="optional smoke-test cap")
    parser.add_argument("--train-backbone", dest="freeze_backbone", action="store_false")
    parser.add_argument("--freeze-backbone", dest="freeze_backbone", action="store_true")
    parser.add_argument("--allow-cpu", action="store_true", help="explicitly allow very slow CPU fine-tuning")
    parser.add_argument("--overwrite", action="store_true")
    parser.set_defaults(freeze_backbone=True)
    args = parser.parse_args()

    if not args.manifest.is_file():
        parser.error(f"Shared subject-layer manifest does not exist: {args.manifest}; prepare it with the Florence caption script first")
    rows = _read_manifest(args.manifest.resolve())
    summary = {
        "manifest": str(args.manifest.resolve()),
        "photos": len(rows),
        "split_counts": dict(Counter(row["split"] for row in rows)),
        "categories": dict(Counter(row["category"] for row in rows)),
        "human_reviewed": sum(bool(row.get("human_reviewed")) for row in rows),
        "valid_primary_boxes": len(rows),
        "category_fallback_prompt_photos": sum(_grounding_phrase(row)[1] for row in rows),
        "dry_run": args.dry_run,
    }
    if args.dry_run:
        print(json.dumps(summary, ensure_ascii=False, indent=2), flush=True)
    if args.train:
        if args.dry_run:
            parser.error("--dry-run cannot be combined with --train")
        if args.epochs < 1 or args.patience < 1:
            parser.error("epochs and patience must be positive")
        print(json.dumps(_train(args), ensure_ascii=False, indent=2), flush=True)
    if not args.dry_run and not args.train:
        parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
